### ISSUE TITLE
2022-10-26 日内容尚未更新

### ISSUE THREAD

**Issue by HuangJian** [zhaoolee/garss#20]
https://zhaoolee.com/garss/#/ 仍显示昨日内容

> Github Actions Rss (garss, 嘎RSS! 已收集231个RSS源, 生成时间: 2022-10-25 06:27:38)

**Comment by zhaoolee** [comment]
> https://zhaoolee.com/garss/#/ 仍显示昨日内容
> 
> > Github Actions Rss (garss, 嘎RSS! 已收集231个RSS源, 生成时间: 2022-10-25 06:27:38)

Github 镜像的问题，现在修复了，重新Pull一下https://github.com/zhaoolee/garss/blob/main/.github/workflows/main.yml 就好了 
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/15868458/198869606-50a876ad-1744-444d-99fc-5e5e77b0eb93.png">
